"""delete sub_plan column for movie

Revision ID: a751fd360b91
Revises: 0377717a3ac5
Create Date: 2024-06-21 10:34:43.438852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a751fd360b91'
down_revision = '0377717a3ac5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_column('sub_plan')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_plan', sa.VARCHAR(length=20), nullable=False))

    # ### end Alembic commands ###
